name: CI
run-name: Continuous Integration

env:
  NODE_VERSION: "16"

# Run CI whenever there is a PR or push to main.
on:
  push:
    # Add branch itself for testing
    branches: [$default-branch, "6-set-up-cicd"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [$default-branch]

jobs:
  lint_and_test:
    name: Lint and run unit tests using vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      # Cache pnpm artifacts
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker unit tests image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: "export_coverage"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          output: out/coverage/
  static_analysis:
    name: Static analysis with SonarCloud
    runs-on: ubuntu-latest
    needs: [lint_and_test]
    steps:
      - uses: actions/checkout@v3
        with:
          # disabled shallow clones for a better relevancy of analysis
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e_testing:
    name: Run E2E tests with playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      # Cache pnpm artifacts
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker unit tests image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: "playwright_tests"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
