name: send-deploy-event
run-name: Continuous Deployment

# Only trigger when the delivery workflow succeeded
on:
  workflow_run:
    workflows: ["delivery"]
    types:
      - completed

jobs:
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    # only run on PRs and if delivery was successful
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Set SHORT_SHA env var that image was tagged with in delivery pipeline
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Dispatch deploy-event to gcp repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GCP_REPO_PAT }}
          repository: username/my-repo
          event-type: my-event
